### ISSUE TITLE
Why does it couldn't work on dbp15k?

### ISSUE THREAD

**Issue by passermyh** [Xiefeng69/GAEA#1]
![image](https://github.com/Xiefeng69/GAEA/assets/71198047/dd427c5b-d855-4bd4-b6c7-0a19e22755a1)
Thanks for your work!
    I've reproduced the main results mentioned in your paper. However, when I try to run this code on dbp15k , it seems something wrong occured. Why does it happen?

**Comment by passermyh** [comment]
![image](https://github.com/Xiefeng69/GAEA/assets/71198047/66562d23-ccc6-40db-b201-2f063d403857)
I've collected rel_ids and ref/sup_ent

**Comment by Xiefeng69** [comment]
Hello :)
Now that this bug has been fixed, you can see the diff between the previous version and the current version to understand the code changes. The main reason is that, although dbp datasets give each entity an id, this id may be repeated. Therefore, we need to manually assign globally unique ids to entities in different KG to ensure that the subsequent algorithm can be correct.
Best wishes~
